---
ConfigFile: ''
leftBarLinks: 
resourceLinks:
port: 9090
maxLookBack: 1109600000000000
keepMinorNodeUpdates: false
defaultNamespace: default
defaultKind: Deployment
defaultLookback: 3h
threshold for GC: 0.75
badgerDiscardRatio: 0.80
badgerVLogMaxEntries: 150000
badgerUseLSMOnlyOptions: true
